# permissions for end users to view dnsrecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnsrecord-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multicluster-gateway-controller
    app.kubernetes.io/part-of: multicluster-gateway-controller
    app.kubernetes.io/managed-by: kustomize
  name: dnsrecord-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - dnsrecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - dnsrecords/status
  verbs:
  - get
