# permissions for end users to view managedzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: managedzone-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multicluster-gateway-controller
    app.kubernetes.io/part-of: multicluster-gateway-controller
    app.kubernetes.io/managed-by: kustomize
  name: managedzone-viewer-role
rules:
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones/status
  verbs:
  - get
