---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pc-manager-role
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - clusterissuers
  verbs:
  - get
  - list
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - get
  - list
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - dnshealthcheckprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - dnshealthcheckprobes/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - dnshealthcheckprobes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - dnspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - dnspolicies/finalizers
  verbs:
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - dnspolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - dnsrecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - dnsrecords/finalizers
  verbs:
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - dnsrecords/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones/finalizers
  verbs:
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - managedzones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies/finalizers
  verbs:
  - update
- apiGroups:
  - kuadrant.io
  resources:
  - tlspolicies/status
  verbs:
  - get
  - patch
  - update
